# Generated by Django 5.1.2 on 2025-02-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Fruit', 'Fruit'), ('Vegetable', 'Vegetable'), ('Bakery', 'Bakery'), ('Oil', 'Oil'), ('Canned Food', 'Canned Food'), ('Sauces', 'Sauces'), ('Cereal', 'Cereal'), ('Condiment', 'Condiment'), ('Dairy', 'Dairy'), ('Drink', 'Drink'), ('Dry Goods', 'Dry Goods'), ('Frozen Food', 'Frozen Food'), ('Meat', 'Meat'), ('Pasta', 'Pasta'), ('Dry Fruits', 'Dry Fruits'), ('Snacks', 'Snacks'), ('Spices', 'Spices'), ('Herbs', 'Herbs'), ('Ready-to-eat Meals', 'Ready To Eat Meals'), ('Seafood', 'Seafood'), ('Desserts', 'Desserts'), ('Pickled Items', 'Pickled Items'), ('Non-alcoholic Drinks', 'Non Alcoholic Drinks'), ('Baking Ingredients', 'Baking Ingredients'), ('Other', 'Other')], max_length=20)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('standard_expiry_days', models.IntegerField(blank=True, null=True)),
                ('allergy_tags', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
