# Generated by Django 5.1.2 on 2025-03-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_brand_remove_product_quantity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DAIRY', 'Dairy'), ('MEAT_AND_FISH', 'Meat and Fish'), ('VEGETABLE', 'Vegetable'), ('FRUIT', 'Fruit'), ('GRAIN', 'Grain'), ('OTHER', 'Other'), ('BAKERY', 'Bakery'), ('OIL', 'Oil'), ('CANNED_FOOD', 'Canned Food'), ('SAUCES', 'Sauces'), ('CEREAL', 'Cereal'), ('CONDIMENT', 'Condiment'), ('DRINK', 'Drink'), ('DRY_GOODS', 'Dry Goods'), ('FROZEN_FOOD', 'Frozen Food'), ('PASTA', 'Pasta'), ('DRY_FRUITS', 'Dry Fruits'), ('SNACKS', 'Snacks'), ('SPICES', 'Spices'), ('HERBS', 'Herbs'), ('READY-TO-EAT_MEALS', 'Ready-to-eat Meals'), ('SEAFOOD', 'Seafood'), ('DESSERTS', 'Desserts'), ('PICKLED_ITEMS', 'Pickled Items'), ('BAKING_INGREDIENTS', 'Baking Ingredients'), ('MEAT', 'Meat')], max_length=20),
        ),
    ]
