# Generated by Django 5.1.2 on 2025-02-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('time_to_cook', models.IntegerField()),
                ('difficulty', models.CharField(max_length=255)),
                ('servings', models.IntegerField(null=True)),
                ('description', models.TextField()),
                ('cuisine_tags', models.JSONField()),
                ('ingredients', models.JSONField()),
                ('instructions', models.JSONField()),
            ],
        ),
    ]
