# Generated by Django 5.1.2 on 2025-02-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cuisines',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
