# Generated by Django 5.1.2 on 2025-01-03 21:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('age', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('preferences', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('VEGAN', 'Vegan'), ('VEGETARIAN', 'Vegetarian'), ('NON_VEGETARIAN', 'Non-Vegetarian'), ('GLUTEN_FREE', 'Gluten Free'), ('DAIRY_FREE', 'Dairy Free'), ('NONE', 'None')], max_length=20), blank=True, size=None)),
            ],
        ),
    ]
