# Generated by Django 5.1.2 on 2025-01-04 21:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('VEGAN', 'Vegan'), ('VEGETARIAN', 'Vegetarian'), ('NON_VEGETARIAN', 'Non-Vegetarian'), ('GLUTEN_FREE', 'Gluten Free'), ('DAIRY_FREE', 'Dairy Free'), ('NONE', 'None')], max_length=20), blank=True, null=True, size=None),
        ),
    ]
