# Generated by Django 4.2 on 2025-02-02 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userproduct',
            old_name='user_id',
            new_name='user',
        ),
    ]
