# Generated by Django 4.2 on 2025-02-05 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0006_wishlistproduct_wishlistproduct_user_product_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('recipe_type', models.SlugField(blank=True, choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], max_length=2, null=True)),
                ('recipe_time', models.CharField(blank=True, max_length=100, null=True)),
                ('meal_type', models.SlugField(blank=True, choices=[(1, 'Dinner'), (2, 'Breakfast'), (3, 'Lunch')], max_length=2, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('ingredients', models.JSONField(blank=True, default={}, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_auth.cuisine')),
            ],
        ),
        migrations.CreateModel(
            name='FavRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_auth.meals')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_user_recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='favrecipes',
            constraint=models.UniqueConstraint(fields=('recipes', 'user'), name='user_recipes_unique'),
        ),
    ]
