# Generated by Django 4.2 on 2025-02-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0007_cuisine_meals_favrecipes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='steps',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='ingredients',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
