# Generated by Django 4.2 on 2025-02-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0008_meals_steps_alter_meals_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='ingredients',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='steps',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
