# Generated by Django 4.2 on 2025-02-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0010_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisine',
            name='image_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='meals',
            name='image_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
