# Generated by Django 4.2 on 2025-02-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0011_cuisine_image_url_meals_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
    ]
