# Generated by Django 4.2 on 2025-02-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0012_alter_entry_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='subname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
