# Generated by Django 4.2 on 2025-02-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0014_alter_cuisine_image_url_alter_meals_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
