# Generated by Django 4.2 on 2025-02-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0015_alter_meals_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='quantity_type',
            field=models.CharField(choices=[('KG', 'Kilogram'), ('GRAM', 'Gram'), ('LITRE', 'Litre'), ('ML', 'Millilitre'), ('PIECE', 'Piece')], default='KG', max_length=50),
        ),
    ]
