# Generated by Django 4.2 on 2025-02-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0017_alter_meals_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='servings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
