# Generated by Django 4.2 on 2025-02-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0018_meals_servings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='subtitle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
